# Generated by Django 4.2.16 on 2024-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(),
        ),
    ]
